include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for LTE
LUCI_DEPENDS:=+luci-base +uqmi +luci-proto-qmi

PKG_MAINTAINER:=Seeed
PKG_LICENSE:=Apache-2.0
PKG_VERSION:=1.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
