include $(TOPDIR)/rules.mk

LUCI_TITLE:=MultiWAN Manager
LUCI_DEPENDS:=+luci-base +mwan3
PKG_MAINTAINER:= Seeed
PKG_LICENSE:=Apache-2.0
PKG_VERSION:=1.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
