include $(TOPDIR)/rules.mk

LUCI_TITLE:=Cellular Configuration
LUCI_DEPENDS:=+luci-base +lte-serve
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature