#!/bin/sh
# Delete existing bridge and LAN configuration
uci delete network.lan
uci delete network.@device[0]
uci commit network

# Set network configuration
uci set network.loopback=interface
uci set network.loopback.device='lo'
uci set network.loopback.proto='static'
uci set network.loopback.ipaddr='127.0.0.1'
uci set network.loopback.netmask='255.0.0.0'
uci set network.globals=globals
uci set network.globals.ula_prefix='fdf4:628a:1dc9::/48'
uci set network.wan=interface
uci set network.wan.device='eth0'
uci set network.wan.proto='dhcp'
uci set network.LTE=interface
uci set network.LTE.proto='qmi'
uci set network.LTE.device='/dev/cdc-wdm0'
uci set network.LTE.auth='none'
uci set network.LTE.pdptype='ipv4v6'
uci set network.wlan=interface
uci set network.wlan.proto='static'
uci set network.wlan.type='bridge'
uci set network.wlan.ipaddr='192.168.2.1'
uci set network.wlan.netmask='255.255.255.0'
uci set network.wlan.device='wlan0'
uci set network.wwan=interface
uci set network.wwan.proto='dhcp'
uci set network.wwan.device='wlan0'
uci commit network

# Set firewall rules
uci add firewall rule
uci set firewall.@rule[-1].name='Allow-WAN-HTTP'
uci set firewall.@rule[-1].src='wan'
uci set firewall.@rule[-1].proto='tcp'
uci set firewall.@rule[-1].dest_port='80'
uci set firewall.@rule[-1].target='ACCEPT'
uci set firewall.@rule[-1].family='ipv4'
uci add firewall rule
uci set firewall.@rule[-1].name='Allow-ssh-WAN'
uci set firewall.@rule[-1].src='wan'
uci set firewall.@rule[-1].proto='tcp'
uci set firewall.@rule[-1].dest_port='22'
uci set firewall.@rule[-1].target='ACCEPT'
uci set firewall.@rule[-1].family='ipv4'
uci add firewall rule
uci set firewall.@rule[-1].name='Allow-WAN-CHIRPSTACK'
uci set firewall.@rule[-1].src='wan'
uci set firewall.@rule[-1].proto='tcp'
uci set firewall.@rule[-1].dest_port='8080'
uci set firewall.@rule[-1].target='ACCEPT'
uci set firewall.@rule[-1].family='ipv4'
uci add firewall rule
uci set firewall.@rule[-1].name='Allow-WAN-TTY'
uci set firewall.@rule[-1].src='wan'
uci set firewall.@rule[-1].proto='tcp'
uci set firewall.@rule[-1].dest_port='7681'
uci set firewall.@rule[-1].target='ACCEPT'
uci set firewall.@rule[-1].family='ipv4'
uci add_list firewall.@zone[0].network='wlan'
uci commit firewall

# Set dhcp configuration
uci set dhcp.wlan=dhcp
uci set dhcp.wlan.interface='wlan'
uci set dhcp.wlan.start='100'
uci set dhcp.wlan.limit='150'
uci set dhcp.wlan.leasetime='12h'
uci set dhcp.wlan.force='1'
uci set dhcp.wlan.netmask='255.255.255.0'
uci commit dhcp

# Set mwan3 for multi-wan failover (priority: wan > LTE > wlan)
# Delete default
uci -q delete mwan3.wan6
uci -q delete mwan3.wanb
uci -q delete mwan3.wanb6
uci -q delete mwan3.wan_m2_w3
uci -q delete mwan3.wanb_m1_w2
uci -q delete mwan3.wanb_m1_w3
uci -q delete mwan3.wanb_m2_w2
uci -q delete mwan3.wan6_m1_w3
uci -q delete mwan3.wan6_m2_w3
uci -q delete mwan3.wanb6_m1_w2
uci -q delete mwan3.wanb6_m1_w3
uci -q delete mwan3.wanb6_m2_w2
uci -q delete mwan3.wan_only
uci -q delete mwan3.wanb_only
uci -q delete mwan3.balanced
uci -q delete mwan3.wan_wanb
uci -q delete mwan3.wanb_wan
# wan interface
uci set mwan3.wan=interface
uci set mwan3.wan.enabled='1'
uci set mwan3.wan.initial_state='online'
uci set mwan3.wan.family='ipv4'
uci set mwan3.wan.track_method='ping'
uci set mwan3.wan.reliability='1'
uci set mwan3.wan.count='1'
uci set mwan3.wan.size='56'
uci set mwan3.wan.max_ttl='60'
uci set mwan3.wan.check_quality='0'
uci set mwan3.wan.timeout='2'
uci set mwan3.wan.interval='5'
uci set mwan3.wan.failure_interval='5'
uci set mwan3.wan.recovery_interval='5'
uci set mwan3.wan.down='3'
uci set mwan3.wan.up='3'
uci add_list mwan3.wan.track_ip='8.8.8.8'
uci add_list mwan3.wan.track_ip='1.1.1.1'
# LTE interface
uci set mwan3.LTE=interface
uci set mwan3.LTE.enabled='1'
uci set mwan3.LTE.initial_state='online'
uci set mwan3.LTE.family='ipv4'
uci set mwan3.LTE.track_method='ping'
uci set mwan3.LTE.reliability='1'
uci set mwan3.LTE.count='1'
uci set mwan3.LTE.size='56'
uci set mwan3.LTE.max_ttl='60'
uci set mwan3.LTE.check_quality='0'
uci set mwan3.LTE.timeout='2'
uci set mwan3.LTE.interval='5'
uci set mwan3.LTE.failure_interval='5'
uci set mwan3.LTE.recovery_interval='5'
uci set mwan3.LTE.down='3'
uci set mwan3.LTE.up='3'
uci add_list mwan3.LTE.track_ip='8.8.8.8'
uci add_list mwan3.LTE.track_ip='1.1.1.1'
# wwan interface (lowest priority)
uci set mwan3.wwan=interface
uci set mwan3.wwan.enabled='1'
uci set mwan3.wwan.initial_state='online'
uci set mwan3.wwan.family='ipv4'
uci set mwan3.wwan.track_method='ping'
uci set mwan3.wwan.reliability='1'
uci set mwan3.wwan.count='1'
uci set mwan3.wwan.size='56'
uci set mwan3.wwan.max_ttl='60'
uci set mwan3.wwan.check_quality='0'
uci set mwan3.wwan.timeout='2'
uci set mwan3.wwan.interval='5'
uci set mwan3.wwan.failure_interval='5'
uci set mwan3.wwan.recovery_interval='5'
uci set mwan3.wwan.down='3'
uci set mwan3.wwan.up='3'
uci add_list mwan3.wwan.track_ip='8.8.8.8'
uci add_list mwan3.wwan.track_ip='1.1.1.1'
# members with metric (metric determines priority)
uci set mwan3.wan_m1_w3=member
uci set mwan3.wan_m1_w3.interface='wan'
uci set mwan3.wan_m1_w3.metric='1'
uci set mwan3.wan_m1_w3.weight='3'
uci set mwan3.LTE_m2_w3=member
uci set mwan3.LTE_m2_w3.interface='LTE'
uci set mwan3.LTE_m2_w3.metric='2'
uci set mwan3.LTE_m2_w3.weight='3'
uci set mwan3.wwan_m3_w3=member
uci set mwan3.wwan_m3_w3.interface='wwan'
uci set mwan3.wwan_m3_w3.metric='3'
uci set mwan3.wwan_m3_w3.weight='3'
# Cfailover policy
uci set mwan3.failover_policy=policy
uci add_list mwan3.failover_policy.use_member='wan_m1_w3'
uci add_list mwan3.failover_policy.use_member='LTE_m2_w3'
uci add_list mwan3.failover_policy.use_member='wwan_m3_w3'
#default rule
uci set mwan3.default_rule_v4=rule
uci set mwan3.default_rule_v4.dest_ip='0.0.0.0/0'
uci set mwan3.default_rule_v4.use_policy='failover_policy'
uci set mwan3.default_rule_v4.family='ipv4'
uci commit mwan3

# Set rpcd login 
uci set rpcd.@login[0].username='admin'
uci commit rpcd

# Set system hostname
uci set system.@system[0].hostname='SenseCAP'
uci commit system

# Restart services
/etc/init.d/network restart
/etc/init.d/firewall restart
/etc/init.d/rpcd restart
/etc/init.d/mwan3 restart
/etc/init.d/dnsmasq restart