include $(TOPDIR)/rules.mk

LUCI_TITLE:=RS485 Configuration
LUCI_DEPENDS:=+luci-base +rs485-module
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature